create table if not exists public.page_visits (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  visited_at timestamptz not null default now()
);

create index if not exists page_visits_visited_at_idx on public.page_visits (visited_at desc);
alter table public.page_visits enable row level security;

drop policy if exists "Anonymous visitors can record visits" on public.page_visits;
create policy "Anonymous visitors can record visits"
on public.page_visits for insert to anon with check (true);

drop policy if exists "Authenticated admin can read visits" on public.page_visits;
create policy "Authenticated admin can read visits"
on public.page_visits for select to authenticated using (true);
