"use client";
import Image from "next/image";
import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, ArrowUpDown, MessageCircle, X } from "lucide-react";
import type { Category, Product } from "@/lib/types";
import { formatGuarani, whatsappUrl } from "@/lib/format";

const filters: readonly ["todos" | Category, string][] = [["todos","Todo"],["entradas","Aperitivos"],["fideos_arroz","Fideos y arroz"],["currys_sopas","Currys y sopas"],["pescados","Pescados"],["especialidades","Especialidades"],["postres","Postres"],["bebidas","Bebidas"]];

export function Catalog({ products }: { products: Product[] }) {
  const [active,setActive]=useState<"todos"|Category>("todos"); const [sort,setSort]=useState<"none"|"asc"|"desc">("none"); const [selected,setSelected]=useState<Product|null>(null);
  const shown=useMemo(()=>{const result=products.filter((item)=>active==="todos"||item.category===active);return sort==="none"?result:[...result].sort((a,b)=>sort==="asc"?a.price-b.price:b.price-a.price)},[products,active,sort]);
  const cards=(items:Product[])=><div className="grid">{items.map((item)=><article className="card" key={item.id}><button className="image-wrap product-image-button" onClick={()=>setSelected(item)} aria-label={`Ver ${item.name}`}><Image src={item.image_url} alt={item.name} fill sizes="(max-width: 640px) 50vw, 33vw"/></button><div className="card-body"><div className="meta">{item.reference}</div><h3>{item.name}</h3>{item.short_note&&<p className="details">{item.short_note}</p>}{item.sizes&&<p className="details product-variants">{item.sizes}</p>}<div className="price">{item.sizes?`Desde ${formatGuarani(item.price)}`:formatGuarani(item.price)}</div><a className="whatsapp" href={whatsappUrl(item.name,item.reference,item.price)} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Consultar</a></div></article>)}</div>;
  return <><header className="thai-header"><div className="shell thai-nav"><a href="#inicio" className="thai-wordmark"><Image src="/brand/papa-muay-thai-logo.webp" width={58} height={58} alt="Papa Muay Thai Resort"/><span>PAPA MUAY THAI</span></a><a href={whatsappUrl()} target="_blank" rel="noreferrer"><MessageCircle/> Consultar</a></div></header><section className="thai-hero" id="inicio"><div className="shell"><span className="eyebrow">Cocina tailandesa</span><h1>Sabores de Tailandia,<br/><em>más cerca.</em></h1><p>Explorá el menú y consultá directamente por WhatsApp.</p><a className="primary" href="#menu">Ver menú</a></div></section><main className="shell catalog" id="menu"><div className="catalog-heading"><div><span className="eyebrow">Nuestro menú</span><h2>Elegí tu favorito</h2></div><span className="count">{shown.length} productos</span></div><div className="filters">{filters.map(([value,label])=><button key={value} className={active===value?"active":""} onClick={()=>setActive(value)}>{label}</button>)}<button className={`price-sort ${sort!=="none"?"active":""}`} onClick={()=>setSort(sort==="none"?"asc":sort==="asc"?"desc":"none")}>Precio {sort==="asc"?<ArrowUp size={14}/>:sort==="desc"?<ArrowDown size={14}/>:<ArrowUpDown size={14}/>}</button></div>{active==="todos"&&sort==="none"?<div className="category-groups">{filters.slice(1).map(([value,label])=>{const items=products.filter((item)=>item.category===value);if(!items.length)return null;return <section className="category-section" key={value}><div className="category-title"><h3>{label}</h3><span>{items.length} productos</span></div>{cards(items)}</section>})}</div>:cards(shown)}</main><section className="thai-cta"><div className="shell"><span>¿Querés hacer un pedido?</span><h2>Escribinos por WhatsApp</h2><a href={whatsappUrl()} target="_blank" rel="noreferrer"><MessageCircle/> Consultar</a></div></section><footer className="thai-footer shell"><span className="thai-footer-brand"><Image src="/brand/papa-muay-thai-logo.webp" width={48} height={48} alt="Papa Muay Thai Resort"/><strong>PAPA MUAY THAI</strong></span><a href="https://wendelo.online" target="_blank" rel="noreferrer"><Image src="/brand/wendelo-mark.png" width={20} height={18} alt=""/> Producto de wendelo.online</a></footer>{selected&&<div className="product-lightbox" role="dialog" aria-modal="true" onClick={()=>setSelected(null)}><div className="lightbox-panel" onClick={(event)=>event.stopPropagation()}><button className="lightbox-close" onClick={()=>setSelected(null)}><X/></button><div className="lightbox-image"><Image src={selected.image_url} alt={selected.name} fill sizes="95vw"/></div><div className="lightbox-caption"><strong>{selected.name}</strong><span>{formatGuarani(selected.price)}</span></div><a className="lightbox-share" href={whatsappUrl(selected.name,selected.reference,selected.price)} target="_blank"><MessageCircle size={18}/> Consultar</a></div></div>}</>;
}
